# 这是一个示例的spdlog配置文件
sp_logger:
  name: rotating_logger
  level: info
  sinks:
    - type: rotating_file_sink
      filename: "/home/user/.ros/log/my_node.log"
      max_size: 10485760  # 10MB
      max_files: 5
  pattern: "[%Y-%m-%d %H:%M:%S.%e] [%l] %v"
