global:
  level: info         # 全局日志级别，默认为 info，可以根据需要设置为 debug, warn, error 等
  flush_on: error     # 定义何时刷新日志，可以设置为 trace, debug, info, warn, error, critical

# 日志记录器配置
sinks:
  - name: rotating_logger
    type: rotating_file_sink
    filename: "/path/to/log/directory/my_node.log"  # 请替换为实际的日志路径
    max_size: 10485760  # 最大日志文件大小为 10MB
    max_files: 5        # 最大保留 5 个轮转日志文件

  # 启用异步日志记录器（可选）
  - name: async_logger
    type: async
    queue_size: 8192   # 队列大小，影响日志吞吐量和丢失风险
    threads: 1         # 异步日志的工作线程数

loggers:
  - name: rotating_logger
    level: info          # 设置此记录器的日志级别
    sinks: ["rotating_logger"]
    async: true          # 启用异步模式
  - name: async_logger
    level: debug         # 可以根据需要调整异步记录器的日志级别
    sinks: ["async_logger"]
    async: true
